package create_account;

import javafx.fxml.FXML;

import javafx.scene.input.MouseEvent;

public class CreateAccountController {

	// Event Listener on Button.onMouseClicked
	@FXML
	public void backToLogin(MouseEvent event) {
		// TODO Autogenerated
	}
}
